### ISSUE TITLE
issue with installing

### ISSUE THREAD

**Issue by iaval** [mhammell-laboratory/TEsmall#3]
Dear,
I would like to try to use your tool, but I am running into some issues with installing it. Using miniconda, I get an error after this step: conda env create -f environment.txt -n tesmall.
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
 - matplotlib==1.5.1
 - bokeh==0.12.2

I guess the versions of these packages are so old that it can't install them properly. Is there a way to use new versions? Or I can install these version, but would TEsmall recognize them when they are not in miniconda? Thank you for you help!
Best wishes,
Iris

**Comment by wwliao** [comment]
Hi Iris,

Thanks for reporting. I've updated the versions of matplotlib and bokeh in the environment.txt file, so it should work now. Could you please try again?
Thanks!

**Comment by iaval** [comment]
Hi Wen-Wei,

Thanks for replying so quickly! I have tried it again and it did get a step further than last time. But it seemed to still not work, this is the message I get after using the same command:

Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.                                                                                fa                                                                                                        iled                                                                                                                               \

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 32, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 281, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 808, in _run_sat
        should_retry_solve=ssc.should_retry_solve
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 1318, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/home/iris/miniconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

**Comment by wwliao** [comment]
Hi Iris,

I can't reproduce the same error, so need more info to figure it out.
Did you get this error when running `python setup.py install`? If so, did you activate the conda environment using `source activate tesmall` or `conda activate tesmall` first?

**Comment by wwliao** [comment]
Looks like you got the error when running `conda env create -f environment.txt -n tesmall`. Could you update your conda using `conda update -n base conda` and remove the previous tesmall environment using `conda env remove -n tesmall`, then try `conda env create -f environment.txt -n tesmall` again?
I tried to install it in my laptop (MacOS) and everything works fine.

**Comment by iaval** [comment]
Hi Wen-Wei,
I got the error while creating the tesmall environment. I have now updated conda and removed the potential old environment. When I try to run `conda env create -f environment.txt -n tesmall` again, I still get an error that several specifications are incompatible with each other
[error.txt](https://github.com/mhammell-laboratory/TEsmall/files/4355407/error.txt)
. So it is unable to create the environment. I am working on a Ubuntu server. 
Thank you again for your help!

**Comment by wwliao** [comment]
Hi Iris,

Sorry for the late reply.
It turns out the issue is because conda remove the `free` channel from the `defaults` channel leading to a lot of older packages can't be accessed anymore.
I restored the versions of matplotlib and bokeh in the environment.txt. Now the only thing you need to do is create a conda environment using `CONDA_RESTORE_FREE_CHANNEL=1 conda env create -f environment.txt -n tesmall`. Hoping you won't get any other issues (I've installed TEsmall on a Linux server successfully).

Thanks!

**Comment by iaval** [comment]
Hi Wen-Wei,
Thank you again for helping me! The installation worked with your suggested correction. 
Best wishes,
Iris

**Comment by iaval** [comment]
Hi Wen-Wei,
Sorry I have one last question. I would like to use TEsmall with the fly reference. On the website I found that there was a dm3 annotation available, which I downloaded. I tried to specify the location of this dm3 reference using the suggested code:  export TESMALLROOT=/your/desired/directory. But I still got an error:
2020-03-26 16:45:51,575 INFO Checking if reference genome and annotation files exist...
2020-03-26 16:45:51,581 INFO Downloading reference genome and annotation files...
Traceback (most recent call last):
  File "/home/iris/miniconda3/envs/tesmall/bin/tesmall", line 11, in <module>
    load_entry_point('TEsmall==0.4.0', 'console_scripts', 'tesmall')()
  File "/home/iris/.local/lib/python2.7/site-packages/TEsmall-0.4.0-py2.7.egg/tesmall/command_line.py", line 58, in main
    get_requirements(args.genome)
  File "/home/iris/.local/lib/python2.7/site-packages/TEsmall-0.4.0-py2.7.egg/tesmall/settings.py", line 63, in get_requirements
    filepath = join(path, basename(url[genome]))
KeyError: 'dm3'

It is still trying to download the dm3 reference, but might not be able to find it. Would it help if I put the dm3 annotation that I downloaded in a specific directory? 

Thank you again for all your help!
Iris

**Comment by wwliao** [comment]
Hi Iris,

TEsmall recognizes specific directory structure:
```
/your/desired/directory/.tesmall
└── genomes
   └── dm3
      ├── annotation
      │  ├── exon.bed
      │  ├── hairpin.bed
      │  ├── intron.bed
      │  ├── miRNA.bed
      │  ├── piRNA_cluster.bed
      │  ├── structural_RNA.bed
      │  └── TE.bed
      └── sequence
         ├── bowtie_index
         │  ├── genome.1.ebwt
         │  ├── genome.2.ebwt
         │  ├── genome.3.ebwt
         │  ├── genome.4.ebwt
         │  ├── genome.rev.1.ebwt
         │  ├── genome.rev.2.ebwt
         │  ├── rDNA.1.ebwt
         │  ├── rDNA.2.ebwt
         │  ├── rDNA.3.ebwt
         │  ├── rDNA.4.ebwt
         │  ├── rDNA.rev.1.ebwt
         │  └── rDNA.rev.2.ebwt
         ├── genome.fa
         ├── genome.fa.fai
         ├── rDNA.fa
         └── rDNA.fa.fai
```

So I will recommend you just let TEsmall download them automatically (I've updated the code, so now it should be able to download dm3 when you specify it using `-g dm3`) as follows:

```
conda activate tesmall
export TESMALLROOT=/your/desired/directory
tesmall -f sample1.fastq.gz sample2.fastq.gz -g dm3
```

Note that TEsmall will only download the required files if it cannot find them in `/your/desired/directory`, which means if you run it twice, it won't download the same files again.

Let me know if this solves your issue. Thanks!

**Comment by iaval** [comment]
Hi Wen-Wei,
Thank you for getting back to me so quickly. I didn't see the error concerning the dm3 annotation anymore, but unfortunately am still getting another error saying that python 2.7.12 can't be found. But there is this version of python installed. I would really appreciate if you could once again help me out with this issue. 

(tesmall) iris@papagei:~/results/tesmall$ export TESMALLROOT=~/results/tesmall
(tesmall) iris@papagei:~/results/tesmall$ tesmall -f Rep1_control_Input_S1_R1_out.fastq Rep1_control_CID_S3_R1_out.fastq -g dm3 -l Rep1_control_Input Rep1_control_CID -M 75
Traceback (most recent call last):
  File "/home/iris/.local/bin/tesmall", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python==2.7.12' distribution was not found and is required by TEsmall
(tesmall) iris@papagei:~/results/tesmall$ python --version
Python 2.7.12

**Comment by wwliao** [comment]
Hi Iris,

I guess you didn't install TEsmall correctly. Because everything you've installed should be under in the same folder. For example, my tesmall and python are both under `/medseq/wliao/conda_root/envs/tesmall/bin/` as you can see below:

```
wen-wei.liao@blade18-1-15:~$ conda activate tesmall
(tesmall) wen-wei.liao@blade18-1-15:~$ which tesmall
/medseq/wliao/conda_root/envs/tesmall/bin/tesmall
(tesmall) wen-wei.liao@blade18-1-15:~$ which python
/medseq/wliao/conda_root/envs/tesmall/bin/python
```

However, the python you use (`/usr/lib/python2.7/`) isn't the python installed in conda environment. And even the tesmall you use (`/home/iris/.local/bin/tesmall`) doesn't look like it's installed in conda environment either.

**Comment by iaval** [comment]
Hi Wen-Wei,
I am sorry, I indeed installed it incorrectly. I am relatively new with this, so I still have to learn a lot. I now installed it correctly and it all seemed to work well. Thank you for all you help!
Best wishes,
Iris

**Comment by wwliao** [comment]
Hi Iris,

No worries, good to know it works now!

All the best.
